//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_facial_recognition_forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public int Id { get; set; }
        public string LoginUserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
    }
}
